"""add_2fa_fields

Revision ID: 7fa509c22cca
Revises: f185e7b5a654
Create Date: 2026-06-17 03:22:57.684437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa509c22cca'
down_revision: Union[str, Sequence[str], None] = 'f185e7b5a654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor_backup_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('two_factor_backup_codes', schema=None) as batch_op:
        batch_op.create_index('idx_backup_tenant_user', ['tenant_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_two_factor_backup_codes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_two_factor_backup_codes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret_encrypted', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_two_factor_enabled')
        batch_op.drop_column('totp_secret_encrypted')

    with op.batch_alter_table('two_factor_backup_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_two_factor_backup_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_two_factor_backup_codes_tenant_id'))
        batch_op.drop_index('idx_backup_tenant_user')

    op.drop_table('two_factor_backup_codes')
    # ### end Alembic commands ###
