"""Add Serverless Actions table

Revision ID: 0c6bc1fe25e3
Revises: 1654d51f14ed
Create Date: 2026-06-20 08:41:42.532993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c6bc1fe25e3'
down_revision: Union[str, Sequence[str], None] = '1654d51f14ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs_y2026m06', schema=None) as batch_op:
        batch_op.drop_index('audit_logs_y2026m06_tenant_id_idx')
        batch_op.drop_index('audit_logs_y2026m06_tenant_id_timestamp_idx')
        batch_op.drop_index('audit_logs_y2026m06_timestamp_idx')
        batch_op.drop_index('audit_logs_y2026m06_user_id_idx')
        batch_op.drop_index('audit_logs_y2026m06_user_id_timestamp_idx')

    op.drop_table('audit_logs_y2026m06')
    with op.batch_alter_table('audit_logs_y2026m07', schema=None) as batch_op:
        batch_op.drop_index('audit_logs_y2026m07_tenant_id_idx')
        batch_op.drop_index('audit_logs_y2026m07_tenant_id_timestamp_idx')
        batch_op.drop_index('audit_logs_y2026m07_timestamp_idx')
        batch_op.drop_index('audit_logs_y2026m07_user_id_idx')
        batch_op.drop_index('audit_logs_y2026m07_user_id_timestamp_idx')

    op.drop_table('audit_logs_y2026m07')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs_y2026m07',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('device_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='audit_logs_tenant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='audit_logs_y2026m07_pkey')
    )
    with op.batch_alter_table('audit_logs_y2026m07', schema=None) as batch_op:
        batch_op.create_index('audit_logs_y2026m07_user_id_timestamp_idx', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('audit_logs_y2026m07_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('audit_logs_y2026m07_timestamp_idx', ['timestamp'], unique=False)
        batch_op.create_index('audit_logs_y2026m07_tenant_id_timestamp_idx', ['tenant_id', 'timestamp'], unique=False)
        batch_op.create_index('audit_logs_y2026m07_tenant_id_idx', ['tenant_id'], unique=False)

    op.create_table('audit_logs_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('device_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='audit_logs_tenant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'timestamp', name='audit_logs_y2026m06_pkey')
    )
    with op.batch_alter_table('audit_logs_y2026m06', schema=None) as batch_op:
        batch_op.create_index('audit_logs_y2026m06_user_id_timestamp_idx', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('audit_logs_y2026m06_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('audit_logs_y2026m06_timestamp_idx', ['timestamp'], unique=False)
        batch_op.create_index('audit_logs_y2026m06_tenant_id_timestamp_idx', ['tenant_id', 'timestamp'], unique=False)
        batch_op.create_index('audit_logs_y2026m06_tenant_id_idx', ['tenant_id'], unique=False)

    # ### end Alembic commands ###
