"""Add composite indexes and updated_at

Revision ID: 1c0f8cacc7f0
Revises: c7da2e975ce1
Create Date: 2026-06-20 03:31:25.551401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0f8cacc7f0'
down_revision: Union[str, Sequence[str], None] = 'c7da2e975ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_oauth_provider_user')

    with op.batch_alter_table('organization_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('tenant_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_tenant_email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_tenant_email', ['tenant_id', 'email'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('tenant_api_keys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('organization_invites', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_oauth_provider_user', ['provider', 'provider_user_id'], unique=False)

    # ### end Alembic commands ###
