"""Add tenant API keys

Revision ID: 9f31f49c2fdc
Revises: 284e5b715fb1
Create Date: 2026-06-19 21:37:02.515393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f31f49c2fdc'
down_revision: Union[str, Sequence[str], None] = '284e5b715fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_api_keys_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_api_keys_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('ix_tenants_api_key')
        batch_op.drop_column('api_secret_hash')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('api_secret_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.create_index('ix_tenants_api_key', ['api_key'], unique=1)

    with op.batch_alter_table('tenant_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_api_keys_api_key_hash'))

    op.drop_table('tenant_api_keys')
    # ### end Alembic commands ###
