"""Add OrganizationInvite model

Revision ID: c7da2e975ce1
Revises: e9f3952b515f
Create Date: 2026-06-20 03:10:09.307713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7da2e975ce1'
down_revision: Union[str, Sequence[str], None] = 'e9f3952b515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invites_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invites_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_invites_token_hash'))
        batch_op.drop_index(batch_op.f('ix_organization_invites_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_organization_invites_email'))

    op.drop_table('organization_invites')
    # ### end Alembic commands ###
