"""Add device info to sessions

Revision ID: e9f3952b515f
Revises: 9f31f49c2fdc
Create Date: 2026-06-20 03:01:45.303022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f3952b515f'
down_revision: Union[str, Sequence[str], None] = '9f31f49c2fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('os_info', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('browser_info', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('device_type')
        batch_op.drop_column('browser_info')
        batch_op.drop_column('os_info')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
